### ISSUE TITLE
DOC: Convert Python documentation to docstrings

### ISSUE THREAD

**Issue by tturocy** [gambitproject/gambit#336]
### Summary

For 16.1.0 we will convert all the free-standing documentation done by hand in ReST to docstrings, using Numpydoc style.

### Tasks

- [x] #337
- [ ] Convert documentation for action
- [ ] Convert documentation for player
- [ ] Convert documentation for information set
- [ ] Convert documentation for strategy
- [ ] Convert documentation for outcome
- [ ] Convert documentation for node
- [ ] Convert documentation for mixed behaviour profiles
- [ ] Convert documentation for mixed strategy profiles
- [ ] Clean up location of API documentation in index
